  default:
    testnet: true
    port: 7270
    insight:
      livenet:
        confirmations: 6
        url: ['https://insight.bitpay.com:443','https://blockexplorer.com']
      testnet:
        confirmations: 1
        url: ['https://test-insight.bitpay.com:443','https://testnet.blockexplorer.com']
    logging: 
      path: './logs'
      level: info